# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'remote_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TV_Remote(object):
    def setupUi(self, TV_Remote):
        TV_Remote.setObjectName("TV_Remote")
        TV_Remote.resize(320, 500)
        TV_Remote.setMinimumSize(QtCore.QSize(320, 500))
        TV_Remote.setMaximumSize(QtCore.QSize(320, 500))
        TV_Remote.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        TV_Remote.setAnimated(False)
        TV_Remote.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(TV_Remote)
        self.centralwidget.setObjectName("centralwidget")

        self.vol_up = QtWidgets.QPushButton(self.centralwidget)
        self.vol_up.setGeometry(QtCore.QRect(220, 150, 93, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.vol_up.setFont(font)
        self.vol_up.setStyleSheet("background-color: violet")
        self.vol_up.setObjectName("vol_up")

        self.vol_down = QtWidgets.QPushButton(self.centralwidget)
        self.vol_down.setGeometry(QtCore.QRect(220, 180, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.vol_down.setFont(font)
        self.vol_down.setStyleSheet("background-color: violet")
        self.vol_down.setObjectName("vol_down")

        self.ch_down = QtWidgets.QPushButton(self.centralwidget)
        self.ch_down.setGeometry(QtCore.QRect(220, 100, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.ch_down.setFont(font)
        self.ch_down.setStyleSheet("background-color: violet")
        self.ch_down.setObjectName("ch_down")

        self.ch_up = QtWidgets.QPushButton(self.centralwidget)
        self.ch_up.setGeometry(QtCore.QRect(220, 60, 93, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ch_up.setFont(font)
        self.ch_up.setStyleSheet("background-color: violet")
        self.ch_up.setObjectName("ch_up")

        self.pwr = QtWidgets.QPushButton(self.centralwidget)
        self.pwr.setGeometry(QtCore.QRect(120, 10, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pwr.setFont(font)
        self.pwr.setAutoFillBackground(False)
        self.pwr.setStyleSheet("background-color: rgb(255, 85, 0)")
        self.pwr.setCheckable(True)
        self.pwr.setObjectName("pwr")

        self.mute = QtWidgets.QPushButton(self.centralwidget)
        self.mute.setGeometry(QtCore.QRect(240, 220, 51, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.mute.setFont(font)
        self.mute.setStyleSheet("background-color: lightgreen")
        self.mute.setCheckable(True)
        self.mute.setChecked(False)
        self.mute.setObjectName("mute")

        self.key_1 = QtWidgets.QPushButton(self.centralwidget)
        self.key_1.setGeometry(QtCore.QRect(80, 200, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.key_1.setFont(font)
        self.key_1.setStyleSheet("background-color: lightblue")
        self.key_1.setObjectName("key_1")

        self.key_2 = QtWidgets.QPushButton(self.centralwidget)
        self.key_2.setGeometry(QtCore.QRect(150, 200, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.key_2.setFont(font)
        self.key_2.setStyleSheet("background-color: lightblue")
        self.key_2.setObjectName("key_2")

        self.key_0 = QtWidgets.QPushButton(self.centralwidget)
        self.key_0.setGeometry(QtCore.QRect(10, 200, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.key_0.setFont(font)
        self.key_0.setStyleSheet("background-color: lightblue")
        self.key_0.setObjectName("key_0")

        self.volume = QtWidgets.QSlider(self.centralwidget)
        self.volume.setGeometry(QtCore.QRect(20, 80, 160, 22))
        self.volume.setMaximum(2)
        self.volume.setOrientation(QtCore.Qt.Horizontal)
        self.volume.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.volume.setTickInterval(0)
        self.volume.setObjectName("volume")

        self.channel = QtWidgets.QSlider(self.centralwidget)
        self.channel.setGeometry(QtCore.QRect(20, 150, 160, 22))
        self.channel.setMaximum(2)
        self.channel.setOrientation(QtCore.Qt.Horizontal)
        self.channel.setInvertedAppearance(False)
        self.channel.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.channel.setObjectName("channel")

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 100, 16, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(100, 100, 16, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(170, 100, 16, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 170, 16, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(100, 170, 16, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(170, 170, 16, 16))
        self.label_6.setObjectName("label_6")

        self.channel_label = QtWidgets.QLabel(self.centralwidget)
        self.channel_label.setGeometry(QtCore.QRect(80, 130, 55, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.channel_label.setFont(font)
        self.channel_label.setObjectName("channel_label")

        self.volume_label = QtWidgets.QLabel(self.centralwidget)
        self.volume_label.setGeometry(QtCore.QRect(80, 60, 55, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.volume_label.setFont(font)
        self.volume_label.setObjectName("volume_label")

        self.screen = QtWidgets.QLabel(self.centralwidget)
        self.screen.setGeometry(QtCore.QRect(20, 290, 281, 171))
        self.screen.setAutoFillBackground(False)
        self.screen.setText("")
        self.screen.setPixmap(QtGui.QPixmap("black.jpg"))
        self.screen.setScaledContents(True)
        self.screen.setObjectName("screen")

        TV_Remote.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TV_Remote)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 320, 26))
        self.menubar.setObjectName("menubar")
        TV_Remote.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TV_Remote)
        self.statusbar.setObjectName("statusbar")
        TV_Remote.setStatusBar(self.statusbar)

        self.retranslateUi(TV_Remote)
        QtCore.QMetaObject.connectSlotsByName(TV_Remote)

    def retranslateUi(self, TV_Remote):
        _translate = QtCore.QCoreApplication.translate
        TV_Remote.setWindowTitle(_translate("TV_Remote", "TV_Remote"))
        self.vol_up.setText(_translate("TV_Remote", "Volume Up"))
        self.vol_down.setText(_translate("TV_Remote", "Volume Down"))
        self.ch_down.setText(_translate("TV_Remote", "Channel Down"))
        self.ch_up.setText(_translate("TV_Remote", "Channel Up"))
        self.pwr.setText(_translate("TV_Remote", "Power"))
        self.mute.setText(_translate("TV_Remote", "Mute"))
        self.key_1.setText(_translate("TV_Remote", "1"))
        self.key_2.setText(_translate("TV_Remote", "2"))
        self.key_0.setText(_translate("TV_Remote", "0"))
        self.label.setText(_translate("TV_Remote", "0"))
        self.label_2.setText(_translate("TV_Remote", "1"))
        self.label_3.setText(_translate("TV_Remote", "2"))
        self.label_4.setText(_translate("TV_Remote", "0"))
        self.label_5.setText(_translate("TV_Remote", "1"))
        self.label_6.setText(_translate("TV_Remote", "2"))
        self.channel_label.setText(_translate("TV_Remote", "Channel"))
        self.volume_label.setText(_translate("TV_Remote", "Volume"))

    #def action(self):
        #if self.pwr.isChecked() == True:

# I am very dissapointed with myself as there is basically nothing to show besides gui. I could not figure out how to do any of these additions in time for the project to be done
# I will continue to work on this after the semester.


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TV_Remote = QtWidgets.QMainWindow()
    ui = Ui_TV_Remote()
    ui.setupUi(TV_Remote)
    TV_Remote.show()
    sys.exit(app.exec_())
